[common]

## Base service name used for passwords stored by csw-tools in the keyring.
## Modifying this is advanced usage and is typically not needed.
# keyring_service_name = "csw-tools"

## Secure Workload (formerly Tetration) dashboard used for API calls.
## Accepted formats:
##   URL:  https://my-company.tetrationcloud.com
##   FQDN: my-company.tetrationcloud.com
##   Name: my-company
# dashboard = ""

## Verify the dashboard TLS certificate.
## Set to false only when certificate verification must be bypassed.
# dashboard_verify_tls = true

[prune-agents]


[prune-policy]


[sync-collection-rules]
